tournois/tournois/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('tournoisApp.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
]

tournois/tournoisApp/urls.py
from django.urls import path
from . import views

app_name = 'tournament'
urlpatterns = [
    path('',                        views.home,             name='home'),               # home page, simple view
    path('tournament/',             views.tournamentList,   name='tournamentList'),     # list of tournaments, simple view
    path('tournament/<int:pk>',     views.tournamentDetail, name='tournamentDetail'),   # detail of a tournament, simple view
    path('pool/<int:pk>',           views.poolDetail,       name='poolDetail'),         # detail of a pool, simple view
    path('match/<int:pk>',          views.matchDetail,      name='matchDetail'),        # detail of a match, simple view
    path('team/<int:pk>',           views.teamDetail,       name='teamDetail'),         # detail of a team, simple view
    path('addComment/',             views.addComment,       name='addComment'),         # add a comment, only post (redirect to matchDetail if successful, or home otherwise)
    path('removeComment/<int:pk>',  views.removeComment,    name='removeComment'),      # remove a comment, only post (redirect to matchDetail)
    path('editComment/<int:pk>',    views.editComment,      name='editComment'),        # edit a comment, get => view, post redirect to matchDetail
    path('generateMatchs/<int:pk>', views.generateMatchs,   name='generateMatchs'),     # call pool.createAllMatch if condition met, redirect to poolDetail

    path('testMap/',                views.testMap,          name='testMap'),
    path('editMatch/<int:pk>',      views.editMatch,        name='editMatch') # pk == 0 => create new match
]

tournois/tournoisApp/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from .models import Comment, Match

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['Content']
        widgets = {
            "content": Textarea(attrs={"cols": 80, "rows": 3}),
        }
        
class SearchForm(forms.Form):

    query = forms.CharField(max_length=40, label="Recherche", widget=Textarea(attrs={"cols": 30, "rows": 1, "placeholder": "score, date ou équipe"}))


class MatchForm(ModelForm):
    class Meta:
        model = Match
        fields = '__all__'

tournois/tournoisApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from datetime import datetime
from django.contrib.auth.decorators import user_passes_test

from .models import Tournament, Pool, Match, Team, Comment, Point
from .forms import CommentForm, SearchForm, MatchForm

# Create your views here.
def chart(pk):
    label1=[]
    data1=[]
    data11=[]

    pool=Pool.objects.get(id=pk)
    allmatch=pool.match_set.all()
    allteam=pool.getTeamsAndScores().keys()
    for match in allmatch:
        date=str(match.Date)
        label1.append([match.Team1.Name, match.Team2.Name, date[0:10]])
        if (match.Score1):
            data1.append(match.Score1)
        else: # un match non jouer à un score Null
            data1.append(0)
        if (match.Score2):
            data11.append(match.Score2)
        else:
            data11.append(0)


    label2=[]
    data2=[]
    label4=[]
    data4=[]
    data3=[]

    for teams,score in pool.getTeamsAndScores().items():
        label4.append(teams.Name)
        data4.append(score)

    teamsAndScores= pool.getTeamsAndScores()
    allmatch=pool.match_set.all()
    for team in allteam:
        scoreTeam=0
        scoreEncaisse=0
        for match in allmatch:
            if (match.Score1 or match.Score2): #on verifie que au moins un score est non null 
                if match.Team1==team:
                    scoreTeam=+match.Score1
                    scoreEncaisse=+match.Score2
                if match.Team2==team:
                    scoreTeam=+match.Score2
                    scoreEncaisse=+match.Score1
        label2.append(team.Name)
        data2.append(scoreTeam)
        data3.append({"x":scoreEncaisse,"y":scoreTeam,"r":teamsAndScores[team]})
   
    


    context=[label1,data1,data11,label2,data2,data3,label4,data4]
    #context= {"label1":label1,"data1":data1,"data11":data11, "label2":label2,"data2":data2,"label4":label4,"data4":data4}
    return context


def home(request):
    menue = [['Accueil', 'tournament:home'], ['Liste des tournois', 'tournament:tournamentList']]
    if request.method == "POST":
        searchForm = SearchForm(request.POST)
        if searchForm.is_valid():
            query = searchForm.cleaned_data['query']
            #check whether query is a date and search corresponding match
            try:
                isdate = bool(datetime.strptime(query, "%Y-%m-%d"))
            except ValueError:
                isdate = False
            if isdate:
                date=datetime.strptime(query, "%Y-%m-%d").date()
                matchs = Match.objects.filter(Date__date=date)
            #if not a date search for team names or scores
            else :
                matchs = Match.objects.filter(Team1__Name__icontains=query).union(
                    Match.objects.filter(Team2__Name__icontains=query))
                #cherche les match selon un score
                scores = query.split("-")
                if len(scores)==2:
                    matchs = matchs.union(
                        Match.objects.filter(Score1__contains=scores[0], Score2__contains=scores[1])).union(
                            Match.objects.filter(Score2__contains=scores[0], Score1__contains=scores[1]))
                #cherche les matchs selon une opposition
                queries = query.split(" vs ")
                if len(queries)==2:
                    matchs = matchs.union(
                        Match.objects.filter(Team1__Name__icontains=queries[0],Team2__Name__icontains=queries[1])).union(
                            Match.objects.filter(Team2__Name__icontains=queries[0],Team1__Name__icontains=queries[1]))
            matchs=matchs.order_by("Date")
            teams = Team.objects.filter(Name__icontains=query)
            newform = SearchForm()
            context = {"matchs" : matchs, "teams":teams, "form":newform, 'menue': menue}
            template_name = "tournois/SearchResults.html"
            return render(request, template_name, context)
    else :
        searchForm = SearchForm()
        template_name = 'tournois/Home.html'
    return render(request, template_name,{"form":searchForm, "menue": menue})

def tournamentList(request):
    menue = [['Accueil', 'tournament:home'], ['Liste des tournois', 'tournament:tournamentList']]
    template_name = 'tournois/TournamentList.html'
    allTournament = Tournament.objects.all()
    context = {'allTournament' : allTournament, "menue" : menue}
    return render(request, template_name, context)

def tournamentDetail(request, pk):
    menue = [['Accueil', 'tournament:home'], ['Liste des tournois', 'tournament:tournamentList']]
    template_name = 'tournois/TournamentDetail.html'
    tournament = get_object_or_404(Tournament,id=pk)
    rounds = tournament.matchesSortedbyRound()
    

    # Determine the matches based on the previous scores
    for i in range (1,tournament.knockoutPhaseDepth() + 1):
        tournament.generateNextRound(i) 
        tournament.save()

    context = {'tournament': tournament, 'rounds': rounds, 'menue': menue}
    return render(request, template_name, context)

def poolDetail(request, pk):
    template_name = 'tournois/PoolDetail.html'
    pool = get_object_or_404(Pool,id=pk)
    canGenerate = (len(pool.Teams.all()) == pool.Tournois.NBTeamPerPool)
    contextchart=chart(pk)
    menue = [['Accueil', 'tournament:home'], ['Liste des tournois', 'tournament:tournamentList'], [pool.Tournois.Name, "tournament:tournamentDetail", pool.Tournois.id]]
    context = {'pool': pool, 'canGenerate':canGenerate, 'label1':contextchart[0], 'data1':contextchart[1], 'data11':contextchart[2], 'label2':contextchart[3], 'data2':contextchart[4],'data3':contextchart[5], 'label4':contextchart[6],'data4':contextchart[7], 'menue':menue}



    return render(request, template_name, context)

def generateMatchs(request, pk):
    pool = get_object_or_404(Pool,id=pk)
    if (len(pool.match_set.all()) == 0) and (len(pool.Teams.all()) == pool.Tournois.NBTeamPerPool) and (request.user.is_superuser):
        pool.createAllMatch()
        pool.save()
    return HttpResponseRedirect(reverse('tournament:poolDetail',  args=[pool.id]))

"""
    This view displays the tree of the knockout phase of the tournament
    The view is integrated to the TournamentDetail template
"""
def generateMatchTree(request, pk):
    tournament = get_object_or_404(Tournament,id=pk)  
    for i in range (1,tournament.knockoutPhaseDepth() + 1):
        tournament.generateNextRound(i) 
        tournament.save()
    return HttpResponseRedirect(reverse('tournament:tournamentDetail', args=[tournament.id]))


def matchDetail(request, pk):
    template_name = 'tournois/MatchDetail.html'
    match = get_object_or_404(Match,id=pk)
    commentForm = CommentForm()
    menue = [['Accueil', 'tournament:home'], ['Liste des tournois', 'tournament:tournamentList']]
    if (match.Tournament):
        menue += [[match.Tournament.Name, 'tournament:tournamentDetail', match.Tournament.id]]
    elif (match.Pool): # sometimes, match doesn't have a tournament but are in a pool belonging to a tournament
        if (match.Pool.Tournois):
            menue += [[match.Pool.Tournois.Name, 'tournament:tournamentDetail', match.Pool.Tournois.id]]
    if (match.Pool): # lors des eliminatoir, certain match n'ont pas de pool
        menue += [['Poule ' + str(match.Pool.index), 'tournament:poolDetail', match.Pool.id]]
    context = {'match': match, 'commentForm' : commentForm, "menue": menue}
    return render(request, template_name, context)

def teamDetail(request, pk):
    template_name = 'tournois/TeamDetail.html'
    team = get_object_or_404(Team,id=pk)
    matchs = Match.objects.filter(Team1__id__contains=pk).union(Match.objects.filter(Team2__id__contains=pk))
    matchs = matchs.order_by("Date")
    first_match = matchs[0] #pour le menu, poule et tournoi de son premier match (le dernier n'aura pas forcément de poules)
    menue = [['Accueil', 'tournament:home'], ['Liste des tournois', 'tournament:tournamentList']]
    if (first_match):#while creating a pool, a team can have no matchif (match.Tournament):
        if(first_match.Tournament):
            menue += [[first_match.Tournament.Name, 'tournament:tournamentDetail', first_match.Tournament.id]]
        elif (first_match.Pool): # sometimes, first_match doesn't have a tournament but are in a pool belonging to a tournament
            if (first_match.Pool.Tournois):
                menue += [[first_match.Pool.Tournois.Name, 'tournament:tournamentDetail', first_match.Pool.Tournois.id]]
        if (first_match.Pool): # lors des eliminatoir, certain first_match n'ont pas de pool
            menue += [['Poule ' + str(first_match.Pool.index), 'tournament:poolDetail', first_match.Pool.id]]
    context = {'team': team, "matchs":matchs, "first":first_match, "menue": menue}
    return render(request, template_name, context)

@login_required
def addComment(request):
    if (request.method == 'GET') or (not request.user.is_authenticated):
        return HttpResponseRedirect(reverse('tournament:home'))
    form = CommentForm(request.POST)
    if (form.is_valid()):
        user = request.user
        date = timezone.now()
        content = form.cleaned_data["Content"]
        matchId = request.POST["MatchId"]  
        match = Match.objects.get(id=matchId)
        comment = Comment(User=user, Date=date, Content=content, Match=match)
        comment.save()
        return HttpResponseRedirect(reverse('tournament:matchDetail',  args=[matchId]))
    else :
        return HttpResponseRedirect(reverse('tournament:home'))

@login_required
def removeComment(request, pk):
    comment = Comment.objects.get(id=pk)
    matchId = comment.Match.id
    if request.user == comment.User:
        comment.delete()

tournois/tournoisApp/templates/tournois/EditComment.html
{% extends 'base.html' %}

{% block title %}Editeur de commentaire{% endblock title %}

{% block content %}

<div class="topbanner">
    <h1 style="left:5%;">Comment Editor</h1>
</div>
<div class="midbanner" style="text-align: center;position: relative;">
    <div class="separator" style="height: 50px;"></div>

    <div class="itembox" style=" text-align: center; display: inline-block; width: 30%;">
        <form style="position: relative; margin: 1%;" action="{% url 'tournament:editComment' Comment.id %}" method="post">
            {% csrf_token %}
            {{ commentForm }}
            <input type="submit" value="Post the comment">       
    </div>
    <div class="separator" style="height: 100px;"></div>
    </form>
        <div class="box" style="width: 49%; text-align: right;">   
            <h1 style=" color: rgb(10, 77, 104); font-size: 50px;">Old Comment:</h1>
        </div>
        <div class="box" style=" position:relative; width: 49%; text-align: left;">
            <h3>{{Comment}}</h3>
    </div>

    




    <div class="separator" style="height: 400px;"></div>
</div>

{% endblock content %}

tournois/tournoisApp/templates/tournois/EditMatch.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Edit Match{% endblock title %}

{% block content %}
<div class="topbanner">
    <h1>Creation/Modification d'un match</h1>
</div>
<div class="midbanner">
    <div class="box" style="width: 60%">
        <form action="{% url 'tournament:editMatch' id %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Save">
        </form>
    </div>

    <div class="box" style="width: 30%">
    {% include "tournois/MapModule.html" with longitude=match.Longitude lattitude=match.Lattitude %}
    </div>
    <script src="{% static 'mapControl.js' %}"></script>
</div>
{% endblock content %}

tournois/tournoisApp/templates/tournois/Home.html
{% extends 'base.html' %}
{%load static%}
{% block content %}
<div class="topbanner" style="text-align: center; height:50%;" >
        <div style="position:relative; height:200px; width:100%; background-color: transparent;"></div>
        <h1 style="margin:0">TOURNOIS</h1>

</div>

<div style="text-align:center; position: relative; width: 100%; background-color: gray;">
    <h3><a class ="linka"  style="font-size: 30px; color:lightgrey; margin: 0;" href="{% url 'tournament:tournamentList' %}">Aller à la liste des tournois</a></h3>
</div>

<div class="midbanner" >
    <div style="position:relative; height:50px; width:100%; background-color: transparent;"></div>
    <div class="itembox" style="position: relative; margin: auto; width: 40%;">
        <h3 style="font-size:15px;" >Chercher une équipe ou un match:</h3>
        <form method="post" action="{% url 'tournament:home'%}">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Search">
        </form>
    </div>
    <div style="position:relative; height:200px; width:100%; background-color: transparent;"></div>
</div>





{% endblock content %}

tournois/tournoisApp/templates/tournois/MapModule.html
{% load static %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
     integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
     crossorigin=""/>

<!-- Make sure you put this AFTER Leaflet's CSS -->
<script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
     integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM="
     crossorigin=""></script>

<link rel="stylesheet" href="{% static 'map.css' %}">

<div id="map" start-longitude="{{longitude | default:'1.433333'}}" start-lattitude="{{lattitude | default:'43.6'}}" zoom="{{zoom | default:'12'}}" 
{% if longitude %}
start-point="True"
{% endif %}
></div>
<script src="{% static 'map.js' %}"></script>

tournois/tournoisApp/templates/tournois/MatchDetail.html
{% extends 'base.html' %}

{% block title %} {{match.Team1.Name}} VS {{match.Team2.Name}}{% endblock title %}

{% block head %}
{% load static %}
<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock head%}

{% block content %}
<div class="topbanner">
    <h1>{{match.Team1.Name}} VS {{match.Team2.Name}}</h1>
</div>
    

<div class="midbanner">
    <h2 class="infos">Score : <B>{{match.getScoreString}}</B> / Lieu : {{match.Location}} / Date : {{match.Date}} </h2>
    {% if user.is_superuser %} <p><a href="{% url 'tournament:editMatch' match.id %}">edit</a></p>{% endif %}
    <div class="box" style="width: 60%">
        <h3 class="matchtxt"> Commentaires </h3>

        <div class="scrollableitems">
        {% if match.comment_set.all %}
        <ul>
            {% for Comment in match.comment_set.all%}
            <div class="itembox">
            <li>{{Comment}}
                {% if user == Comment.User %}
                    <a href="{% url 'tournament:removeComment' Comment.id %}">delete</a>  
                    <a href="{% url 'tournament:editComment' Comment.id %}">edit</a>
                {% endif %}    
            </li>
            </div>
            <div class="separator">
            </div>
            {% endfor %}
        </ul>
        {% else %}
            <p>Il n'y a pas de commentaires.</p>
        {% endif %}
        <p left:"5%">
            {% if user.is_authenticated %}
            <form action="{% url 'tournament:addComment' %}" method='post'>
                {% csrf_token %}
                {{ commentForm }}
                <input type="hidden" name="MatchId" id="MatchId" value={{match.id}}>
                <input type="submit" value="Post the comment">
            </form>
            {% else %}
            <p left="5%">Vous n'êtes pas connecté. <a href="{% url 'tournament:addComment'%}">Log in</a> to add a comment</p>
            {% endif %}
        </p>
        </div>
    </div>

    <div class = "box" style="30%">
    {% include "tournois/MapModule.html" with longitude=match.Longitude lattitude=match.Lattitude %}
    </div>
</div>
{% endblock content %}

tournois/tournoisApp/templates/tournois/PoolDetail.html
{% extends 'base.html' %}

{%load static%}

{% block title %} {{pool.Tournois.Name}} : poule {{pool.index}}{% endblock title %}

{% block head %}
{% endblock head%}

{% block content %}

<div class="topbanner">
    <div style="position:relative; height:200px; width:100%; background-color: transparent;"></div>
    <h1 style="left:3%;">{{pool.Tournois.Name}} : Poule {{pool.index}}</h1>
</div>

    <div class="midbanner" style="text-align: center;">
        <div class="box" style="width: 60%;">
            <div style="position:relative; height:20px; width:100%; background-color: transparent;"></div>
            <h1 style="left:5%; color: rgb(10, 77, 104); text-align: left;"> Matchs  </h1>
            <div style="position:relative; height:15px; width:100%; background-color: transparent;"></div>

            <div class="scrollableitems">
                {% if pool.match_set.all %}
                <ul>
                    {% for match in pool.match_set.all %}
                    <div class="itembox">
                        <li><a class="linka" href= "{% url 'tournament:matchDetail' match.id %}">{{match.Team1.Name}} VS {{match.Team2.Name}}</a></li>
                        <p> Score : {{match.getScoreString}} / Location : {{match.Location}} / Date : {{match.Date}} </p>
                        {% if user.is_superuser %} <li class="link" style="font-size: 15px;"><a class="linka" href="{% url 'tournament:editMatch' match.id %}">EDIT</a></li>{% endif %}
                    </div>
                    <div class="separator">
                    </div>
                
                
                    {% endfor %}
                    {% if user.is_superuser %} 
                    <div class="itembox" style="width:30%; background-color: #272d4b;">
                    <li><a class="linka" style="font-size: 15px; color:rgb(187, 233, 240) ;" href="{% url 'tournament:editMatch' 0 %}">NOUVEAU MATCH</a></li>
                    </div>
                    <div class="separator">
                    </div>
                    {% endif %}
                </ul>
                {% else %}
                    {% if user.is_superuser %}
                        {% if canGenerate %}
                        <a href="{% url 'tournament:generateMatchs' pool.id %}">generate all matchs</a>
                        {% else %}
                        <p>No match and not the right amount of team in the pool</p>
                        {% endif %}
                    {% else %}
                    <p>Aucun match dans cette poule</p>
                    {% endif %}
                    {% if user.is_superuser %} <p><a href="{% url 'tournament:editMatch' 0 %}">create Match</a></p>{% endif %}
                {% endif %}
                </div>
            </div>    

            <div class="box" style="width:5%"> </div>
            <div class="borded-box" style="width:30%">
            {% if pool.match_set.all %}
            <h3 style="position: relative; 
            text-align: center;
            font-size:40px;
            "> classement </h3>
            <div class="box" style="width: 25%;">
                <h3 style="position: relative; 
                left: 0px; 
                top: 2px;
                text-align: center;
                "> Points</h3>
            </div>
            <div class="box" style="width:5%"> </div>
            <div class="box" style="width: 25%"> 
                <h3 style="position: relative; 
                left: 0px; 
                top: 2px;
                text-align: center;
                "> Equipes </h3>
            </div>

            <div class="separator"></div>

                    {% for team, score in pool.getTeamsAndScores.items %}
                    <div class="box" style="width: 25%; text-align: right;">
                        <li><FONT size="5pt">{{score}}</FONT> 
                    </div>
                    <div class="box" style="width:5%"> </div>
                    <div class="box" style="width:30%"> <li class="link">
                    <a class="linka" href=" {% url 'tournament:teamDetail' team.id %}">{{team.Name}}</a></li>
                    </div>
                    <div class="separator">
                    </div>
                    {% endfor %}
                {% else %}
                <h3 style="position: relative; 
                text-align: center;
                font-size:50px;
                "> équipes </h3>
                <ul>
                    {% for team in pool.Teams.all %}
                    <li class="link"a><a href="{% url 'tournament:teamDetail' team.id %}">{{team.Name}}</a></li>
                    <div class="separator">
                    </div>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            <div style="position:relative; height:100px; width:100%; background-color: transparent;"></div>
            <h3 style="font-size: 40px; color: darkgray;">POOL STATISTICS</h3>
    </div>



    {% include "src/index.html"%}
    </div>


{% endblock content %}

tournois/tournoisApp/templates/tournois/SearchResults.html
{% extends 'base.html' %}
{% block title %}Résultats de recherche{% endblock title %}
{% block content %}
    <div class = "topbanner">
    <h1>Résultats de recherche :</h1>
    </div>

    <div class = "midbanner">
        <p><a href="{% url 'tournament:home' %}">Retour à l'accueil</a></p>
    {%if matchs or teams%}
        {%if teams%}
        <h3>Team : </h3>
          {%for team in teams%}
          <ul>
          <div class="itembox" style="width: 40%; ">
            <li class="link"><a class="linka" style="text-transform: uppercase;" href= "{% url 'tournament:teamDetail' team.id %}">{{team.Name}}</a></li>
            </div>
            </ul>
            {%endfor%}
        {%endif%}
        {%if matchs%}
        <h3>Matchs :</h3>
        <div class="scrollableitems">
            <ul>
            {%for match in matchs%}
            <div class = "itembox">
                    <li><a class="linka" href= "{% url 'tournament:matchDetail' match.id %}">{{match.Team1.Name}} VS {{match.Team2.Name}}</a></li>
                    <p> Score : {{match.getScoreString}} / Location : {{match.Location}} / Date : {{match.Date}} </p>
                    {% if user.is_superuser %} <a class="linka" href="{% url 'tournament:editMatch' match.id %}">edit</a>{% endif %}
                </div>
                <div class="separator">
                </div>
            {%endfor%}
        </ul>
    </div>
        {%endif%}
    {%else%}
    <p></p>Pas de résultats, vérifier le format de la date (YYYY-MM-DD), du score (x-x) ou l'orthographe. Pour chercher une oppposition, écrire vs entre les 2 équipes.</p>
    {%endif%}
    <p> Faire une nouvelle recherche : </p>
    <form method="post" action="{% url 'tournament:home'%}">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Search">
    </form>
</div>

{% endblock content %}

tournois/tournoisApp/templates/tournois/TournamentDetail.html
{% extends 'base.html' %}
{% block title %}Val's Tournament : {{tournament.Name}}{% endblock title %}
{% block head %}
{% endblock head%}

{% block content %}


<div class="topbanner">
    <div style="position:relative; height:200px; background-color: transparent;"></div>
    <h1 style="position: relative; left: 5%;">Liste des tournois</h1>
</div>    
    
<div class="midbanner">
    <h1 style="left:5%; color: rgb(10, 77, 104);">{{tournament.Name}}</h1>
   

    <div class="scrollableitems" style="left:5%; height: 500px;">
        {% if tournament.pool_set.all %}
    <ul>
        {% for pool in tournament.pool_set.all %}
        <div class="itemboxb" >
            <li class="link" style="font-weight: 750; text-transform: uppercase;"><a class="linka" href= "{% url 'tournament:poolDetail' pool.id %}">Poule {{pool.index}}</a></li>
        </div>
        <div class="separator" style="height: 10px;"></div>

            <ul>
                {% for team, score in pool.getTeamsAndScores.items %}
                <li class="link"><a class="linka" href="{% url 'tournament:teamDetail' team.id %}">{{team.Name}}</a></li>
                <div class="separator" style="height: 10px;"></div>
                {% endfor %}
            </ul>
        {% endfor %}
    </ul>
    
    {% if rounds %}
    <h1 style="position: relative; color: rgb(10, 77, 104); text-align: center; font-size: 50px;">Winner Bracket</h1>
    <div style="position:relative; height:5px; background-color: rgb(10, 77, 104);"></div>
        <div class="tree">
            
            {% for round in tournament.matchesSortedbyRound %}
                <div class="round">
                        <table>
                        
                        {% for match in round %}
                            <tr>
                                <td>
                                    <div class="matchbox">
                                        <div class="team">
                                            <div class="box" style="text-align: left; width: 80%;">
                                                <a style= "text-decoration: none; color: rgb(115, 234, 210);" href= "{% url 'tournament:matchDetail' match.id %}">{{match.Team1.Name}}</a>
                                            </div>
                                            <div class="box" style="text-align: right; width: 10%;">
                                                <p style= "text-decoration: none; color: rgb(231, 114, 126);" >{{match.Score1}}</p>
                                            </div>
                                            <br>
                                        </div>
                                        <div class="team">
                                            <div class="box" style="text-align: left; width: 80%;">
                                                <a style= "text-decoration: none; color: rgb(115, 234, 210);" href= "{% url 'tournament:matchDetail' match.id %}">{{match.Team2.Name}}</a>
                                            </div>
                                            <div class="box" style="text-align: right; width: 10%;">
                                                <p style= "text-decoration: none; color: rgb(231, 114, 126);" >{{match.Score2}}</p>
                                            </div>
                                            <br>                                           
    
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            
                        {% endfor %}
                        </table>
                </div>
                
            {% endfor %}      
        </div>
        
    {% else %}
    <p> Les phases éliminatoire de ce tournoi ne sont pas générées</p>
    {% endif %}
    
    
    {% else %}
            
        <p>aucune poule n'est organisée dans ce tournoi</p>
    {% endif %}
    <div style="position:relative; height:50px; background-color: transparent;"></div>
    </div>
{% endblock content %}